### ISSUE TITLE
Drop column not dropping

### ISSUE THREAD

**Issue by sommarin** [parashardhapola/scarf#24] opened 2021-05-18 08:46 UTC
I'm trying to remove a column in cells. Used ds.cells.drop('column_name') and nothing happened.

**Comment by parashardhapola** [comment] 2021-05-19 21:18
Fixed this issue in d5192ff
A newer version, 0.7.3 is now available on PyPi.

Please update Scarf like this:
`pip install -U scarf-toolkit`

Please feel free to close this issue if the problem is resolved on your end.

**Closed** 2021-05-20 06:37 UTC
